// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qgjibjejzwipoequtdlg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFnamliamVqendpcG9lcXV0ZGxnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2MzcyMTQsImV4cCI6MjA2MzIxMzIxNH0.UBPOscRZcLH6KbV4By60RP0HS373dBS_jy1qrrxRB68";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);